apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: demo
  labels:
    app: demo-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: demo-app
