apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: demo
  labels:
    app: demo-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30012
  selector:
    app: demo-app
