apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: demo-
commonLabels:
  app: demo-app
  release: demo
namespace: default
resources:
- ../../base
images:
- name: demo-app
  newName: rabindra01/react_web
  newTag: fe-1718c97bfdc9f219cdbbeee629e99ae3952d9704
