apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: demo-
commonLabels:
  app: demo-app
  release: demo
namespace: demo
resources:
- ../../base
images:
- name: demo-app
  newName: rabindra01/react_web
  newTag: fe-84e6b7e438ddffd36320f8d6609bea753246ee3c
