name: Build/Push Frontend Image - Dev

on:
  push:
    branches:
      - "main"

env:
  REPOSITORY: react_web
permissions: write-all

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        id: docker-login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        id: build-image
       # uses: docker/build-push-action@v2
        env: 
         IMAGE_TAG: fe-${{ github.sha }}
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::${{ secrets.DOCKER_HUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG"
      #  with:
      #    context: .
      #    file: ./Dockerfile
      #    push: true
      #    tags: ${{ secrets.DOCKER_HUB_USERNAME }}/react_web:latest

          
      - name: Setup Kustomize
        id: setup-kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Push Changes to Github
        id: push-changes
        env:
          IMAGE_NAME: ${{ steps.build-image.outputs.image }}
        run: |
          cd /k8s/overlays/dev && kustomize edit set image demo-app=${IMAGE_NAME} && cd -
          git add /k8s/overlays/dev/kustomization.yaml
          git commit -m "[ci/cd] change image name."
          git push origin feature/frontend
